name: Weather ETL

on:
  schedule:
    - cron: "0 * * * *"  # every hour
  workflow_dispatch:      # allow manual trigger

jobs:
  run-etl:
    runs-on: ubuntu-latest

    env:
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_PORT: ${{ secrets.DB_PORT }}

    steps:
      - name: Test Supabase connection
        run: |
          python - <<EOF
          import psycopg2, os, socket
          host = os.getenv("DB_HOST")
          ipv4 = socket.gethostbyname(host)
          conn = psycopg2.connect(
            host=ipv4,
            dbname=os.getenv("DB_NAME"),
            user=os.getenv("DB_USER"),
            password=os.getenv("DB_PASSWORD"),
            port=os.getenv("DB_PORT", 5432),
            sslmode="require"
            )
          print("Connected successfully!")
          conn.close()
          EOF

      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run ETL script
        run: python dags/etl.py
